"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Learn nextjs",
//   description: "Generated by create next app",
//   openGraph:{
//     title: "Learn nextjs",
//     description: "Generated by create next app",
//     url:"monsite.com",
//     siteName:"learnnextjs",
//     images:[
//       {
//         url:"https://example.com/image.jpg",
//         alt:"image",
//         width:800,
//         height:600
//       }
//     ],
//     locale:"fr",
//     type:"website"
//   },
  
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <header className="px-8 py-5 text-xl border-b">diamanka.sn@gmail.com</header> */}
       <div>{children}</div>
       <Toaster richColors position="top-right"/>
      </body>
    </html>
  );
}
